version: "3.7"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - "./common.env"
      - "./pihole/pihole.env"
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)

  homebridge:
    container_name: hb
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    env_file:
      - "./common.env"
      - "./homebridge/hb.env"
    volumes:
      - ./homebridge/config:/homebridge/
    
  ripe-atlas:
      image: jamesits/ripe-atlas:latest
      restart: always
      environment:
        RXTXRPT: "yes"
      env_file:
        - "./common.env"
        # - "./ripe/atlas-probe.env"
      volumes:
        - "./ripe/atlas-probe/etc:/var/atlas-probe/etc"
        - "./ripe/atlas-probe/status:/var/atlas-probe/status"
      cap_drop:
        - ALL
      cap_add:
        - CHOWN
        - SETUID
        - SETGID
        - DAC_OVERRIDE
        - NET_RAW
      # mem_reservation: 64m # disabled as it is unsupported in current environment
      labels:
        - "traefik.enable=false"
        - "com.centurylinklabs.watchtower.enable=true"
      logging:
        driver: json-file
        options:
          max-size: 10m
      network_mode: host # if possible, avoid double NAT
      # security_opt:
      #   - seccomp:unconfined